### PR TITLE
Fix issues with tests

### PR DESCRIPTION
**Pull request by noahrhodes**
Some MRSP tests do not have consistent solutions because many subsets of items can be selected.  Updates remove checking the specific device statuses, and only check that buses are active (to support load) and the objective function.

Removed tests/code for iterative restoration because this algorithm is a work in progress and does not belong in the package yet.

### CODE REVIEW

**Comment by noahrhodes** [comment]
There is one MLD test that results in `termination_status=NUMERICAL_ERROR`.

`result = run_mld(case3_mld_lc, PowerModels.ACPPowerModel, ipopt_solver)`

@ccoffrin Do you have an advice for addressing this test?

**Comment by ccoffrin** [comment]
RE `NUMERICAL_ERROR`, in this case I usually comment out the test and add a comment note like this, https://github.com/lanl-ansi/PowerModels.jl/blob/460b310288787d4196f9e50b1a81127ee4677a97/test/pf.jl#L19

**Comment by ccoffrin** [comment]
Seems to pass tests without any issue.  What was the `NUMERICAL_ERROR` bit about?

**Comment by noahrhodes** [comment]
It gave a numerical error when I tested locally, but interesting that it passed on CI.

**Comment by ccoffrin** [comment]
Probably there was an update to one of the solvers and you have a slightly older version.  In case case, I am going to merge so we can look into the other PR.

**Pull request merged**
