### PR TITLE
Simplify Iter Solver Result Building

### PR DESCRIPTION
**Pull request by ccoffrin**
@noahrhodes, as far as I can tell this is a correct implementation of the results file, but I know you changed this recently.  What am I missing?

### CODE REVIEW

**Comment by noahrhodes** [comment]
`merge_solution` does not combine the data dictionary in the two solutions.  (this is what I was running into when I wanted to check energy not served)

I believe the reported solution here will not have a data dictionary  in a multi-network format with all required time-periods.

**Comment by ccoffrin** [comment]
I think there is a confusion about the specification of the result dict.  The value in "data" is usually just some metadata about the instance.  For example, see here,

https://github.com/lanl-ansi/PowerModels.jl/blob/v0.14.3/src/core/solution.jl#L39

If you would like to return the mn_network data it should be returned as another field in the result dict.  However, that approach would also not be consistent with the standard `run_*` methods.  In general they should be single-network-data-in/single-network-solution-out or multi-network-data-in/multi-network-solution-out.  So that calling `update_data!` with the solution is well defined.

**Comment by ccoffrin** [comment]
Also I am considering removing the "data" field from the results becouse I don't think it is very useful at this point.

**Comment by noahrhodes** [comment]
That would be my confusion...that  "data" should be a copy of the input data.


Then it will be fine

**Comment by ccoffrin** [comment]
Ok great.  I will merge this once travis passes.

**Pull request merged**
