### PR TITLE
Restoration simulation

### PR DESCRIPTION
**Pull request by noahrhodes**
WIP: `run_restoration_simulation()` is complete.  Tests need to be written.

Somehow the `random_repair_heuristic` tests are failing even though I made no changes to it.

### CODE REVIEW

**Comment by noahrhodes** [comment]
@ccoffrin

**Comment by noahrhodes** [comment]
@ccoffrin 

There is an issue with branch flow constraints when a bus is inactive.  `constraint_ohms_yt_to` cannot find the variable index for a a branch that connects to a damaged bus.

How did you address this for SOC and AC bus damage in the restoration case?  Does this easily translate to `restoration_simulation` with needing to reference any binary variables for damage?

**Comment by ccoffrin** [comment]
@noahrhodes, yes that is a required condition of the current models.  An ROP solution should always restore buses before their connecting components, so this would not be an issue in a feasible solution.  I can imagine that the issue appears in heuristic solutions like `random_repair_heuristic`.  In these cases a candidate restoration plan can be corrected by delaying a component's restoration until its connecting buses have been restored.

**Comment by noahrhodes** [comment]
Right, I didn't fully think that through

**Comment by noahrhodes** [comment]
The heuristic tests have been removed.  They aren't necessary for the paper, so I'm ignoring it for now.

restoration_simulation now uses a network input file, removes any damage indicator (assume the status value is accurate) and runs `run_rop` on the network.  If no damaged items exist, no binary variables are created. The tests successfully use Ipopt to solve the restore in this way.  

@ccoffrin Thoughts?

**Pull request merged**
