### PR TITLE
Update ROP Revisions

### PR DESCRIPTION
**Pull request by ccoffrin**
@noahrhodes FYI working on some updates.

### CODE REVIEW

**Comment by noahrhodes** [comment]
Once this is merged, I also have the 'iterative rop' to push onto this.

**Comment by ccoffrin** [comment]
@noahrhodes I am done with this for now.  Please review and merge at your convenience.

There is still a bug lurking some where, in the 5 bus example I was developing the nonlinear relaxations cannot serve all of the loads even when all components are restored.

**Comment by ccoffrin** [comment]
It looks like Juniper can get lucky on the AC msrp problem.  The test can be relaxed so that it passes in both cases.

**Comment by noahrhodes** [comment]
@ccoffrin you cleaned up a lot.  LGTM.

By 'get lucky' do you mean the AC MRSP occasionally finds a more optimal solution? Therefore, the fix being that total_generators on <= x, etc.?

**Comment by ccoffrin** [comment]
Yes that is correct, some times (seemingly at random) Juniper finds a solution that is 1 less that it usually finds.  The fix is to make the tests within a range rather than strictly equal.

**Pull request merged**
